// Placement test ("test out"): a short quiz on a topic you say you already know. It is stored
// as a lesson with origin placement, so the answers schedule reviews and measure mastery.
import { z } from 'zod'
import { GeneratedQuestion, lessonProblems } from '../../../shared/lessons'
import type { Db } from '../db/connection'
import { createLesson } from '../services/lessons'
import { requireLiveTopic } from '../services/topics'
import { callStructured } from './client'
import { topicContext } from './lessons'

export const PLACEMENT_QUESTIONS = { min: 5, max: 12 }

export const PlacementOutput = z.object({
  scope: z.string().min(1).max(1500).describe('Markdown: two or three sentences on what this test covers and at what depth'),
  questions: z.array(GeneratedQuestion),
})
export type PlacementOutput = z.infer<typeof PlacementOutput>

export function placementBlocks(out: PlacementOutput) {
  return [
    { type: 'concept' as const, id: null, title: 'What this test covers', body_markdown: out.scope, callout: null },
    ...out.questions,
  ]
}

export function checkPlacement(out: PlacementOutput): string[] {
  const problems = lessonProblems(placementBlocks(out), { requireProject: false })
  const n = out.questions.length
  if (n < PLACEMENT_QUESTIONS.min || n > PLACEMENT_QUESTIONS.max) {
    problems.push(`write ${PLACEMENT_QUESTIONS.min} to ${PLACEMENT_QUESTIONS.max} questions, not ${n}`)
  }
  return problems
}

export async function generatePlacement(db: Db, topicId: string): Promise<{ lessonId: string; runId: string }> {
  const topic = requireLiveTopic(db, topicId)
  const { runId, result } = await callStructured(db, {
    task: 'placement',
    promptName: 'placement',
    schema: PlacementOutput,
    input: { ...topicContext(db, topicId), status_you_set: topic.status_override },
    check: checkPlacement,
    effort: 'high',
  })
  const { lessonId } = createLesson(db, {
    topicId,
    title: `Placement test: ${topic.title}`,
    origin: 'placement',
    blocks: placementBlocks(result),
    createdBy: 'ai',
    aiRunId: runId,
    changeNote: 'Generated by Test out',
  })
  return { lessonId, runId }
}
