import { StrictMode, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const articles = [
  { id:'dimensional-modelling', category:'Data engineering', title:'Dimensional modelling', description:'Facts in the centre. Context around them. A visual guide to Kimball concepts.', status:'In progress', progress:62, time:'12 min read', accent:'ochre', tags:['Kimball','BigQuery','Data modelling'], sections:[
    { id:'mental-model', label:'01', title:'Start with the business question', body:'The most useful starting point is not a table. It is the question you want to answer. “I want to analyse sales by customer, product, store and date” already tells you the shape of the model.', callout:'Facts answer “what happened / how much?” Dimensions answer “who / what / where / when / why?”', visual:'star' },
    { id:'workflow', label:'02', title:'A clearer modelling workflow', body:'The order matters because the grain is the contract that keeps every later decision honest.', steps:[['Choose a process','Sales, orders, shipments, claims, sessions or marketing impressions.'],['Declare the grain','State exactly what one fact row means: one row per product on one transaction.'],['Identify dimensions','What will users filter, group or slice by? Date, customer, product, channel, promotion.'],['Identify facts','What numeric measurements are valid at that grain? Units, revenue, cost, discount.']] },
    { id:'facts-dimensions', label:'03', title:'What goes where?', body:'A fact table records an event at a declared grain. Dimensions hold the descriptive context that makes the event useful to analyse.', visual:'schema' },
    { id:'denormalisation', label:'04', title:'The dimension becomes the flat table', body:'Kimball is not saying the fact becomes a dimension. Descriptive hierarchies are usually flattened into a wide dimension so an analyst can filter product → category → department without walking a chain of joins.', visual:'hierarchy', callout:'In BigQuery, a denormalised dimension often makes the common analytical query simpler and avoids repeated joins through small lookup tables.' },
    { id:'conformed', label:'05', title:'Conformed dimensions create a shared language', body:'A conformed dimension is reused consistently by multiple business processes. Sales and returns can both use the same product definition, so “category” means the same thing in both analyses.', visual:'conformed' },
    { id:'your-context', label:'06', title:'How this maps to your work', body:'For marketing decisioning, the event might be an impression or a customer session. The grain has to be explicit before calculating response rate, attribution or uplift.', visual:'marketing', callout:'Example grain: one row per customer × offer × impression timestamp. Customer, offer, channel and date are dimensions; impressed, clicked, converted and value are facts.' },
  ]},
  { id:'cdc', category:'Data engineering', title:'Change data capture', description:'A future article on moving source-system changes into analytical systems reliably.', status:'Planned', progress:0, time:'Coming soon', accent:'sage', tags:['Pipelines','Streaming'], sections:[] },
  { id:'reinforcement-learning', category:'Machine learning', title:'Reinforcement learning for marketing', description:'A practical mental model for states, actions, rewards and long-term customer value.', status:'Planned', progress:0, time:'Coming soon', accent:'lavender', tags:['RL','Decisioning'], sections:[] },
  { id:'networking', category:'Cloud & platform', title:'Cloud networking fundamentals', description:'A place to connect CIDR, routing, VPNs, VPCs and managed services to real architectures.', status:'Planned', progress:0, time:'Coming soon', accent:'blue', tags:['GCP','Architecture'], sections:[] },
]

function Icon({ name }) { const icons={search:'⌕',book:'▤',bookmark:'▱',arrow:'↗',check:'✓',spark:'✦',menu:'☰'}; return <span className={`icon icon-${name}`} aria-hidden="true">{icons[name]}</span> }
function ProgressRing({ value }) { return <div className="progress-ring" style={{'--progress':`${value*3.6}deg`}}><span>{value}%</span></div> }
function Visual({ type }) {
  if (type==='star') return <div className="star-visual"><div className="node fact-node"><b>fact_sales</b><small>what happened?</small><span>quantity · revenue · cost</span></div><div className="node n-date">dim_date<small>when?</small></div><div className="node n-customer">dim_customer<small>who?</small></div><div className="node n-product">dim_product<small>what?</small></div><div className="node n-store">dim_store<small>where?</small></div></div>
  if (type==='schema') return <div className="schema-grid"><div className="schema-code"><b>fact_sales</b><br/>date_key · FK<br/>customer_key · FK<br/>product_key · FK<br/>store_key · FK<br/><hr/>quantity<br/>revenue<br/>cost</div><div className="schema-code"><b>dim_product</b><br/>product_key · PK<br/>product_name<br/>brand<br/>category<br/>department</div><div className="schema-note"><span>FACT</span> measures the event<br/><span>DIMENSION</span> describes the event</div></div>
  if (type==='hierarchy') return <div className="hierarchy"><div>product</div><b>→</b><div>subcategory</div><b>→</b><div>category</div><b>→</b><div>department</div><section><small>becomes one easy-to-query dimension</small><strong>dim_product</strong><p>product · subcategory · category · department · brand</p></section></div>
  if (type==='conformed') return <div className="conformed"><div><b>fact_sales</b><small>product_key</small></div><strong>dim_product</strong><div><b>fact_returns</b><small>product_key</small></div></div>
  if (type==='marketing') return <div className="marketing-grid"><div><small>EVENT</small><b>impression</b><span>customer × offer × time</span></div><div><small>CONTEXT</small><b>dimensions</b><span>customer · offer · channel</span></div><div><small>OUTCOME</small><b>facts</b><span>click · conversion · value</span></div></div>
  return null
}
function Article({ article, onBack }) {
  const [completed,setCompleted]=useState(article.progress>=100); const [saved,setSaved]=useState(false)
  if (!article.sections.length) return <main className="article empty-article"><button className="back-button" onClick={onBack}>← Back to library</button><div className={`empty-hero ${article.accent}`}><span className="eyebrow">{article.category}</span><h1>{article.title}</h1><p>{article.description}</p><span className="status-badge">{article.status}</span></div><div className="empty-message"><Icon name="spark"/><h2>This article is on the roadmap.</h2><p>The template is ready for it. Add a section, example, and a note about how it connects to your own work.</p></div></main>
  return <main className="article"><button className="back-button" onClick={onBack}>← Back to library</button><div className="article-heading"><div><span className="eyebrow">{article.category} / {article.time}</span><h1>{article.title}</h1><p className="intro">{article.description}</p><div className="tag-row">{article.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div><button className={`save-button ${saved?'saved':''}`} onClick={()=>setSaved(!saved)}><Icon name="bookmark"/> {saved?'Saved':'Save'}</button></div><div className="article-layout"><aside className="toc"><span>In this article</span>{article.sections.map(section=><a href={`#${section.id}`} key={section.id}><b>{section.label}</b>{section.title}</a>)}<div className="article-progress"><ProgressRing value={completed?100:article.progress}/><div><b>{completed?'Complete':'Your progress'}</b><small>{completed?'Nice work.':'Keep building the mental model.'}</small></div></div></aside><div className="article-body">{article.sections.map(section=><section className="article-section" id={section.id} key={section.id}><div className="section-number">{section.label}</div><div><h2>{section.title}</h2><p>{section.body}</p>{section.steps&&<div className="steps">{section.steps.map(([title,text],index)=><div className="step" key={title}><span>{index+1}</span><div><b>{title}</b><p>{text}</p></div></div>)}</div>}{section.visual&&<Visual type={section.visual}/>} {section.callout&&<div className="callout"><Icon name="spark"/><p>{section.callout}</p></div>}</div></section>)}<div className="finish-card"><div><span className="eyebrow">Study checkpoint</span><h2>Does the model make more sense now?</h2><p>Mark the article complete when you can explain the grain of your own event table in one sentence.</p></div><button onClick={()=>setCompleted(!completed)}>{completed?<><Icon name="check"/> Completed</>:'Mark complete'}</button></div></div></div></main>
}
function Library({ onSelect }) {
  const [query,setQuery]=useState(''); const [filter,setFilter]=useState('All topics'); const categories=['All topics',...new Set(articles.map(article=>article.category))]
  const filtered=useMemo(()=>articles.filter(article=>(filter==='All topics'||article.category===filter)&&`${article.title} ${article.description} ${article.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())),[filter,query])
  return <main className="library"><div className="library-top"><div><span className="eyebrow">Your learning system</span><h1>Make the hard things <em>click.</em></h1><p>Personal notes, practical examples, and mental models for the topics you want to master.</p></div><div className="streak"><span>✦</span><b>3 day</b><small>learning streak</small></div></div><div className="stats"><div><b>12</b><span>topics planned</span></div><div><b>1</b><span>article in progress</span></div><div><b>62%</b><span>current progress</span></div></div><div className="library-tools"><div className="search"><Icon name="search"/><input aria-label="Search topics" placeholder="Search your topics" value={query} onChange={event=>setQuery(event.target.value)}/></div><div className="filters">{categories.map(category=><button className={filter===category?'active':''} onClick={()=>setFilter(category)} key={category}>{category}</button>)}</div></div><div className="section-label"><span>Topics</span><small>{filtered.length} of {articles.length} shown</small></div><div className="article-grid">{filtered.map(article=><button className={`article-card ${article.accent}`} onClick={()=>onSelect(article)} key={article.id}><div className="card-top"><span className="category">{article.category}</span><span className="card-arrow"><Icon name="arrow"/></span></div><h2>{article.title}</h2><p>{article.description}</p><div className="card-bottom"><span className={`status ${article.status==='In progress'?'active':''}`}>{article.status}</span>{article.progress>0&&<span className="card-progress">{article.progress}%</span>}</div><div className="progress-bar"><span style={{width:`${article.progress}%`}}/></div></button>)}</div></main>
}
function App() { const [selected,setSelected]=useState(null); const [mobileNav,setMobileNav]=useState(false); return <div className="app"><header className="topbar"><button className="mobile-menu" onClick={()=>setMobileNav(!mobileNav)}><Icon name="menu"/></button><button className="wordmark" onClick={()=>setSelected(null)}><span className="mark">L</span><span>Learning<br/><b>Studio</b></span></button><nav className={mobileNav?'open':''}><button className={!selected?'nav-active':''} onClick={()=>{setSelected(null);setMobileNav(false)}}><Icon name="book"/> Library</button><button><Icon name="bookmark"/> Bookmarks <small>0</small></button></nav><div className="profile"><span className="avatar">MC</span><span>Manuel</span><b>⌄</b></div></header>{selected?<Article article={selected} onBack={()=>setSelected(null)}/>:<Library onSelect={setSelected}/>}<footer><span>Learning Studio</span><span>Built for understanding, not collecting tabs.</span></footer></div> }
createRoot(document.getElementById('root')).render(<StrictMode><App/></StrictMode>)
